version: '3'

services:
  onlineshopdb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=onlineshopdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 6603:3306
    expose:
      - '6603'
    volumes:
      - /data/mysql
  spring-demo:
    image: spring-demo
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - onlineshopdb
    ports:
      - 8080:8080
    expose:
      - '8080'
    volumes:
      - /data/spring-demo